# Coding Quiz #1

## 1부터 100 사이의 홀수와 짝수의 누적합을 구하시오. (10점)

In [ ]:
even_sum = 0
odd_sum = 0

for i in range(1, 101):
  if i % 2 == 0:
    even_sum = even_sum + i
  else:
    odd_sum += i

print(even_sum)
print(odd_sum)# 코드 입력

2550
2500

## 2부터 100 사이의 소수를 구하는 코드를 작성하시오. (30점)

In [ ]:
for i in range(2, 101):
  if i == 2:
    list = [2]
  else:
    for j in range(2,i):
      if i % j == 0:
        break
      elif j == i - 1:
        list.extend([i])
print(list)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

## 가장 짧은 도시 이름을 출력하는 코드를 작성하시오. (30점)

In [ ]:
cities = ['daejeon', 'seoul', 'daegu', 'busan', 'chuncheon', 'uijeongbu']
list = []
cities_lowname=[]
for i in range (0,len(cities)):
    list.extend([len(cities[i])])
for i in range (0,len(cities)):
  if len(cities[i]) == min(list):
    cities_lowname.extend([cities[i]])

print(cities_lowname)
  
    
# 코드 입력

['seoul', 'daegu', 'busan']

## 나이에 따른 입장료를 계산하는 코드를 작성하시오. (30점)

* 1~7세: 1000원
* 8~20세: 2000원
* 21~40세: 3000원
* 41~세: 1500원

In [ ]:
age = 17
pay = 0

if age <= 7:
  pay = 1000
elif age <= 20:
  pay = 2000
elif age <= 40:
  pay = 3000
else:
  pay = 1500
# 코드 입력

print("나이: {0}, 입장료: {1}".format(age, pay))

나이: 17, 입장료: 2000